integrate mayhem
mayhemheroes/rapidcsv pull request #1
Opened 2022-05-26 03:47 UTC by jbgreenh

2022-07-23 23:42 UTC, xansec requested changes
Please make the requested changes.

2022-07-23 23:42 UTC, xansec commented on Mayhemfile
> +project: jbgreenh/rapidcsv
Tests has been changed to testsuite. Please also use a generic project name.

2022-07-23 23:42 UTC, xansec commented on tests-mayhem/nohdr.csv
> +64.529999,64.800003,64.139999,64.620003,21705200,64.620003
This is a fine seed, just keep in mind the tests -> testsuite change of the latest release.

2022-07-26 04:34 UTC, jbgreenh commented on Mayhemfile
> +project: jbgreenh/rapidcsv
updated

2022-07-27 02:17 UTC, xansec approved these changes
LGTM!

2022-07-27 02:17 UTC, merged